apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-server
  name: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  strategy: {}
  template:
    metadata:
      labels:
        app: web-server
    spec:
      serviceAccountName: default
      volumes:
      - name: vol
        emptyDir: {}
      containers:
      - image: replace
        name: devsecops-container
        imagePullPolicy: Always
        ports:
          - containerPort: 8080 
        volumeMounts:
          - mountPath: /tmp
            name: vol
        securityContext:
          capabilities:
            drop:
             - NET_RAW
          runAsUser: 100
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        resources:
         requests:
          memory: "256Mi"
          cpu: "200m"
         limits:
          memory: "512Mi"
          cpu: "500m"          
      imagePullSecrets:
           - name: regcred
        
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-server
  name: web-server
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-server
  type: ClusterIP
